cmake -G"Visual Studio 15 2017" \
    -DLIBC=ON \
    -DSDL_ATOMIC=OFF \
    -DSDL_AUDIO=OFF \
    -DSDL_EVENTS=OFF \
    -DSDL_JOYSTICK=OFF \
    -DSDL_HAPTIC=OFF \
    -DSDL_POWER=OFF \
    -DSDL_FILESYSTEM=OFF \
    -DSDL_THREADS=OFF \
    -DSDL_TIMERS=OFF \
    -DSDL_FILE=OFF \
    -DRENDER_D3D=ON \
    -DSDL_SHARED=OFF \
    -DSDL_STATIC=ON \
    -DVIDEO_OPENGL=OFF \
    -DVIDEO_OPENGLES=OFF \
    -DVIDEO_DUMMY=OFF \
    -DVIDEO_VULKAN=OFF \
    ..
